
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 07 23:31:21 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 9;
  public static final int CHAR = 27;
  public static final int NOTEQUAL = 39;
  public static final int GREATER = 36;
  public static final int LPAREN = 14;
  public static final int SEMI = 6;
  public static final int CONTINUE = 20;
  public static final int LESS = 37;
  public static final int MINUS = 33;
  public static final int RPAREN = 15;
  public static final int AND = 34;
  public static final int LESSEQUAL = 41;
  public static final int OR = 35;
  public static final int BOOL = 26;
  public static final int COMMA = 8;
  public static final int CLASS = 13;
  public static final int INC = 30;
  public static final int DOUBLEDOT = 50;
  public static final int DIV = 43;
  public static final int PLUS = 32;
  public static final int IF = 28;
  public static final int THIS = 45;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int LSQUARES = 10;
  public static final int RETURN = 21;
  public static final int EQUAL = 7;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int MUL = 42;
  public static final int PERCENT = 44;
  public static final int NUMBER = 24;
  public static final int BREAK = 19;
  public static final int IDENT = 25;
  public static final int VOID = 5;
  public static final int GREATEREQUAL = 40;
  public static final int ARROW = 49;
  public static final int FOREACH = 47;
  public static final int LBRACE = 3;
  public static final int ELSE = 29;
  public static final int ENUM = 46;
  public static final int READ = 16;
  public static final int WHILE = 18;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int IFEQUAL = 38;
  public static final int DEC = 31;
  public static final int RSQUARES = 11;
  public static final int DO = 48;
  public static final int PRINT = 17;
}

